### ISSUE TITLE
Still not up and running

### ISSUE THREAD

**Issue by mjtarr** [hjdhjd/homebridge-myq2#63] opened 2020-07-04 19:58 UTC
So uninstalled plugin. Rebooted everything to be careful. Reinstalled.

Now I get:

7/4/2020, 3:46:47 PM Bridge is running on port 51826.7/4/2020, 3:51:45 PM Got SIGINT, shutting down Bridge...7/4/2020, 3:51:49 PM Loaded plugin "homebridge-myq2".7/4/2020, 3:51:49 PM The requested platform "myQ" was not registered by any plugin.7/4/2020, 3:51:49 PM Your config.json is requesting the platform "myQ" which has not been published by any installed plugins.

Went to advanced configuration and changed myQ to myQ2, I get this:

7/4/2020, 3:51:49 PM Bridge is running on port 51826.7/4/2020, 3:54:53 PM Got SIGINT, shutting down Bridge...7/4/2020, 3:54:57 PM Loaded plugin "homebridge-myq2".7/4/2020, 3:54:57 PM The requested platform "myQ2" was not registered by any plugin.7/4/2020, 3:54:57 PM Your config.json is requesting the platform "myQ2" which has not been published by any installed plugins.

Hmmm...

Still not seeing any accessories in HOOBS.

**Comment by abraver** [comment] 2020-07-04 20:38
This is a duplicate of #54 and #59 which are both closed, but I am still having the same issue.

**Comment by gizmotronic** [comment] 2020-07-04 21:17
Which version of Homebridge are you running?

I'm able to load the plugin with 1.0.2 and 1.1.1 (the current version), but it fails with exactly this error on Homebridge 0.4.53.

**Comment by mjtarr** [comment] 2020-07-04 21:31
I am running 

HOOBS Version | 3.2.6
and
Node Version | 12.13.1

Not sure how that relates to homebridge...

**Comment by gizmotronic** [comment] 2020-07-04 23:02
Unfortunately, neither of those are directly related.

I spun an instance of HOOBS up in my Kubernetes cluster and poked around at it. There was no mention of a Homebridge version anywhere. So, I dug around in the provided Terminal. I found HAP-NodeJS, but couldn't find the actual homebridge package. This suggests that it's based on a pre-1.x version, and won't load current plugins.

**Comment by hjdhjd** [comment] 2020-07-05 00:52
@gizmotronic Seems like a reasonable assumption. This is a refactored modern plugin for Homebridge 1.0+ at this point...I'm sure they'll catch up eventually.

**Comment by mjtarr** [comment] 2020-07-05 02:29
Thanks. Will try a direct homebridge install.

-m

**Comment by abraver** [comment] 2020-07-05 19:06
[Over on Reddit](https://www.reddit.com/r/HOOBS/comments/hldk8w/myq2_the_requested_platform_myq_was_not/), I got a suggested solution, though it would require the dev to make a small change (literally like 20 characters).

The ScreenLogic plugin [had the same issue](https://github.com/schemers/homebridge-screenlogic/issues/8), and the HOOBS folks submitted [a pull request](https://github.com/schemers/homebridge-screenlogic/pull/9) which should fix the issue for both HOOBS and earlier versions of Homebridge by changing from

``api.registerPlatform(PLATFORM_NAME, ScreenLogicPlatform)``
to
``api.registerPlatform("homebridge-screenlogic", PLATFORM_NAME, ScreenLogicPlatform)``

If @hjdhjd wouldn't mind making this change, it should fix it for all the HOOBS-ers.

**Comment by hjdhjd** [comment] 2020-07-05 19:08
There will be an update later today to address this. Thanks.

**Comment by hjdhjd** [comment] 2020-07-05 23:24
Give v2.0.11 a shot...

**Comment by abraver** [comment] 2020-07-06 00:30
Success!  Many thanks :)

**Comment by hjdhjd** [comment] 2020-07-06 00:50
Closing this one. Enjoy!

**Closed by hjdhjd** 2020-07-06 00:50 UTC
