### ISSUE TITLE
Sends out notification on HB Restart

### ISSUE THREAD

**Issue by TheEngineerGuy** [hjdhjd/homebridge-myq2#60] opened 2020-07-04 07:49 UTC
When HB restarts, even if the door state hasn't changed, it sends out a notification. Not sure if this is by design, but certainly a change from previous plugin.

Not urgent, just wanted to ask and see what you thought about it.

**Comment by hjdhjd** [comment] 2020-07-04 16:04
It is by design (at the moment). I haven’t decided if I like it or not...open to feedback. The elegant side of my head says “no notifications unless there is something to notify on” and the pragmatic side of my head “hey, it’s just letting me know that it’s working” are having a debate about this one.

Thoughts?

**Comment by TheEngineerGuy** [comment] 2020-07-04 16:13
LOL! Man, I am in the same dilemma now. Thanks for explaining.

I guess we can listen to other people's thoughts.

**Comment by gizmotronic** [comment] 2020-07-04 17:28
If there’s a change in status – say, a door was last known to be closed, but it’s open on restart – I would prefer to know. In any other case it’s unwanted noise for me.

Perhaps this behavior could be configured by a configuration flag?

**Comment by hjdhjd** [comment] 2020-07-04 17:35
This is too esoteric and I don't want to gum up the plugin with too many edge-case options. This is, at best, an annoyance for those who don't want it, and a reassurance to those that do.

Nobody should be relying on this (or most) homebridge plugins to be the universal source of truth. Especially with an undocumented API like this one. It is, by definition, best-effort. :smile:

My inclination is to do something along the lines of what @gizmotronic and make that the default. That said, this isn't high on my list...I have real functionality to reimplement first...but when I do get to this, @gizmotronic outlined the behavior I expect to (eventually) provide.

Closing this one out. Thanks for the discussion!

**Closed by hjdhjd** 2020-07-04 17:35 UTC
