### ISSUE TITLE
Lots of notifications despite no change in state

### ISSUE THREAD

**Issue by Cardo1** [hjdhjd/homebridge-myq2#76] opened 2020-07-07 09:16 UTC
At some point in the last few updates I’ve noticed the plugin has started sending out notifications despite there not being a change of state.

For example, I have various scenes that close the garages, if they’ve been left open.  My “good night” scene turns off all the lights and closes the garages and there’s also a timed scene in the middle of the night that also closes the garages, to mop up in case the “good night” scene wasn’t run and the garages or lights were left open/on.

With the current version of the plugin, even if the garages are already closed, I’m getting notifications telling me the garages have been closed when these scenes are run.  This appears somewhat excessive.  Would it be possible to revert to previous behaviour where notifications are only generated if the state of the garage actually changes?

Thanks.

**Comment by hjdhjd** [comment] 2020-07-10 05:58
@Cardo1 I’m not sure I follow the issue. Can you provide a series of steps I can use to recreate the problematic behavior? I have, in the past and using other plugins and rogue HomeKit accessories (in my case it was an Eve Button that caused all sorts of weird notifications that weren’t tied to it to occur) causing issues. I’m not saying that’s what’s going on here, but it was the first thing that came to mind. If there’s a reproducible use case then I can take a closer look and see if that does the trick.

Thanks!

**Comment by Cardo1** [comment] 2020-07-10 08:43
The notifications are standard HomeKit notifications.

So, in the Home app I have it set to send me notifications when the garage doors open or close.  In the past, the plugin would send me a notification only if the door state actually changed.  If it was closed and I asked it to open and it opened, I would get a notification.  If the door was closed and I asked it to close, I would not get a notification as the door was already closed and there was no change.

Previous behaviour:
Door closed - Request to close - No notification
Door closed - Request to open - Garage opened notification
Door open - Request to close - Garage closed notification
Door open - Request to open - No notification

With the latest plugin, a notification is sent every time a request is made, no matter what state the door was in, to begin with.

So, my automations that close the garages in the night will send “Garage closed” notifications even if the garages were already closed.  Not only does this mean I receive excessive notifications, but it also makes me wonder if I left the garages open when I went to bed!

Thanks for looking into this.

**Comment by bwoodruff** [comment] 2020-07-11 05:02
I'm also experiencing this. I have an automation that attempts to shut the garage door and lock the front door every hour that I'd normally be sleeping. After the recent changes I'm now getting a notification that the garage door was closed every time the automation runs, even though the door is already closed.

**Comment by hjdhjd** [comment] 2020-07-11 14:20
Can you guys share your automations, or create an example automation that I can recreate on my end? I’d appreciate it.

**Comment by Cardo1** [comment] 2020-07-11 14:53
> Can you guys share your automations, or create an example automation that I can recreate on my end? I’d appreciate it.

I’m a bit confused by this request. Any scene that tells the garage to close will do. It doesn’t matter if it’s on a timer or manually activated.

**Comment by hjdhjd** [comment] 2020-07-11 14:56
Well, clearly not any scene, since I know of at least one person (me) who doesn’t have this issue and I have multiple automations tied to the garage door opening or closing. :smile:

Provide an example please.

**Comment by Cardo1** [comment] 2020-07-11 15:02
> Well, clearly not any scene, since I know of at least one person (me) who doesn’t have this issue and I have multiple automations tied to the garage door opening or closing. 😄
> 
> Provide an example please.

I updated my above post. You were a bit quick!
But forget the scenes. Asking Siri on one device to close the garage when the garage is already closed will generate notifications on any other device that has notifications turned on for the garage.

**Comment by hjdhjd** [comment] 2020-07-11 15:03
That’s a simple enough use case to test. I’ll look into it.

**Comment by Cardo1** [comment] 2020-07-11 15:04
> Well, clearly not any scene, since I know of at least one person (me) who doesn’t have this issue and I have multiple automations tied to the garage door opening or closing. 😄
> 
> Provide an example please.

This may seem like a crazy question, but do you have notifications turned on for your garage in the Holme app?

**Comment by hjdhjd** [comment] 2020-07-11 15:04
I just tested this...and can confirm the issue. Alright, I’ll queue this up in the backlog. Thanks.

**Comment by hjdhjd** [comment] 2020-07-11 15:04
@Cardo1 I’m not new to HomeKit. :smile: Yes, thanks.

**Comment by Cardo1** [comment] 2020-07-11 15:05
> @Cardo1 I’m not new to HomeKit. 😄 Yes, thanks.

Just trying to work out why you weren’t seeing the issue! Glad you’ve now witnessed it for yourself.

**Comment by hjdhjd** [comment] 2020-07-11 15:09
I wasn’t seeing the issue because I struggled with the initial description of the problem - it wasn’t very specific on the exact nature of the problem and how to recreate it in an (ideally easily) reproducible way. Chalk it up to miscommunication. :smile:

The comment above solved that. I understood the nature of the problem from your initial description to be related to automation, which it clearly isn’t now that I understand what the crux of the issue you were reporting was.

**Comment by hjdhjd** [comment] 2020-07-12 07:07
This one is fixed, pending the next release. I've got a few more bugs to squash before I push an update out but I wanted to let this thread know. Thanks for reporting it and helping make this plugin better!

**Comment by Cardo1** [comment] 2020-07-12 08:45
> This one is fixed, pending the next release. I've got a few more bugs to squash before I push an update out but I wanted to let this thread know. Thanks for reporting it and helping make this plugin better!

Thanks for all your hard work. Let me know if you’d like a Ko-fi for your efforts.

**Comment by hjdhjd** [comment] 2020-07-12 15:11
Thanks, but I don’t even know what a ko-fi is. :smile:

**Comment by hjdhjd** [comment] 2020-07-12 20:04
All - give v2.1.1 a try, fresh off the presses. Feedback appreciated. Hopefully we got this squashed.

**Comment by Cardo1** [comment] 2020-07-12 20:17
> All - give v2.1.1 a try, fresh off the presses. Feedback appreciated. Hopefully we got this squashed.

Tried updating to 2.1.1 but got a build error and 2.1.1 won’t install.  I’ll try and get a copy of the error...

**Comment by hjdhjd** [comment] 2020-07-12 20:22
Fixed in v2.1.2.

**Comment by hjdhjd** [comment] 2020-07-13 00:06
@Cardo1 can you verify this is fixed when you get a chance and close out this bug report? Thanks!

**Comment by Cardo1** [comment] 2020-07-13 06:13
> @Cardo1 can you verify this is fixed when you get a chance and close out this bug report? Thanks!

The extraneous notifications issue does appear to be fixed, thanks.

However, I have discovered another minor notifications related issue.

When opening the garage, the HK notification is generated when the “garage is opening” rather than when the “garage is open”.
When closing, the HK notification is generated as expected, when the “garage is closed”.

**Comment by hjdhjd** [comment] 2020-07-13 06:19
Thanks for the update...closing this bug out. On the minor point you’re calling out...I understand the perceived issue you’re calling out, but HomeKit controls notifying the end user of state changes...I only control telling them that the state has changed - and saying we are “opening” or “closing” **is** a state change, and this is expected behavior.

Appreciate your thoroughness in reporting. Closing this issue.

**Closed by hjdhjd** 2020-07-13 06:19 UTC

**Comment by Cardo1** [comment] 2020-07-13 06:26
I guess HK decides the door is classed as open as soon as it starts opening, but is only deemed to be closed once it has finished closing.

Hadn’t noticed this behaviour, before, but I guess it makes sense!
