### ISSUE TITLE
after 7/1 I get Error getting MyQ devices: undefined

### ISSUE THREAD

**Issue by bkalai321** [hjdhjd/homebridge-myq2#48] opened 2020-07-03 05:01 UTC
MyQ2 worked until 7/1 now I get Error getting MyQ devices: undefined

**Comment by gizmotronic** [comment] 2020-07-03 05:32
Duplicate of #44

**Comment by hjdhjd** [comment] 2020-07-04 01:41
Update to the latest and it should leverage the v5 API. Thanks.

**Closed by hjdhjd** 2020-07-04 01:41 UTC
