### ISSUE TITLE
state of application deteriorates after day of use

### ISSUE THREAD

**Issue by Kampe** [hjdhjd/homebridge-myq2#82] opened 2020-07-11 00:37 UTC
Start my homebridge server, all is well, myq can be contacted just fine and my devices show as intended.

After a day of runtime, the app is in a bad state, falling over complaining about password being incorrect, and earlier in the log stack was seeing errors generated and received from myq saying call customer support with an ID number to present them.

Any idea how that is occuring?

**Comment by Kampe** [comment] 2020-07-11 05:57
```
homebridge     | [7/10/2020, 12:58:44 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 12:58:58 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 12:58:58 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 12:59:13 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 12:59:13 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 12:59:28 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 12:59:28 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 12:59:43 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 12:59:43 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 12:59:58 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 12:59:58 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 1:00:13 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 1:00:13 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 1:00:28 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 1:00:28 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 1:00:43 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 1:00:43 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 1:00:58 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 1:00:58 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 1:01:13 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 1:01:13 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 1:01:28 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 1:01:28 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 1:01:43 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 1:01:43 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 1:01:58 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 1:01:58 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 1:02:13 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 1:02:13 PM] [myQ] myQ API error: unable to refresh. Will retry later.
homebridge     | [7/10/2020, 1:02:28 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 1:02:28 PM] [myQ] myQ API error: unable to refresh. Will retry later.
```

Keep in mind my device right now is currently contactable and showing in homebridge fine.

**Comment by joebiber** [comment] 2020-07-11 14:31
Same behavior over here, it's solved by a Homebridge restart after which it behaves fine for hours, maybe a day. Next time it does it I will check the MyQ app itself and see what behavior I find there. Kind of feels like a rejection on the MyQ server side after too many connections from homebridge-myq2 ?

**Comment by dxdc** [comment] 2020-07-11 15:19
Same here. Maybe an expired token?

**Comment by hjdhjd** [comment] 2020-07-12 20:11
All - give v2.1.1 a try, fresh off the presses. Feedback appreciated. Hopefully we got this squashed.

**Comment by dxdc** [comment] 2020-07-12 20:12
@hjdhjd Can't wait to try this, thanks! Probably we need to remove `npm run build` from `npm install`... it is causing a failure when using npm -g

```
> homebridge-myq2@2.1.1 install /usr/lib/node_modules/homebridge-myq2
> npm run build

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 65534:1000 "/root/.npm"
glob error { [Error: EACCES: permission denied, scandir '/root/.npm/_logs']
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }
```

**Comment by hjdhjd** [comment] 2020-07-12 20:15
@dxdc LOL. I wonder who added that...:smile: It's taken care of in the repo.

**Comment by dxdc** [comment] 2020-07-12 20:16
🤦

**Comment by hjdhjd** [comment] 2020-07-12 20:22
It's there.

**Comment by DMBlakeley** [comment] 2020-07-12 20:22
Unfortunately the error deleted the plugin ....

**Comment by hjdhjd** [comment] 2020-07-12 20:23
v2.1.2 @DMBlakeley

**Comment by joebiber** [comment] 2020-07-14 20:01
Hey guys ... this did not seem to fix the issue for me. Bummer!

**Comment by dxdc** [comment] 2020-07-14 23:01
@joebiber what do your logs look like?

**Comment by hjdhjd** [comment] 2020-07-14 23:10
@joebiber Can you post additional details? Version of the plugin, logs and exactly what transpired or didn’t? Thanks.

**Comment by dxdc** [comment] 2020-07-14 23:11
@hjdhjd btw, from the logs, mine is getting a token every other day. one other possibility is that the token expired sooner (?) seems odd it would affect different people differently though.

**Comment by hjdhjd** [comment] 2020-07-14 23:12
@dxdc Mine gets a token every 20 hours on the nose. Can you check the timing? Reboots in between or no?

**Comment by dxdc** [comment] 2020-07-14 23:14
You're right, mine does too. I guess you changed the logic?

```
    // Is it time to refresh? If not, we're good for now.
    if((now - this.securityTokenTimestamp) < myqTokenExpirationWindow) {
      return true;
    }
```

**Comment by hjdhjd** [comment] 2020-07-14 23:17
Yes, by design. Best to get a token to be safe...hurts nothing.

That said...@joebiber - please post the requested information above and we can troubleshoot.

**Comment by jiniej** [comment] 2020-07-16 13:51
Hey was planning to come back to post more details later on the same day... got sidetracked, sorry about that. 

I have homebridge running with -D and also myQ debugging enabled and will look out for the next time I get the errors.... I can tell you that without debugging on I was getting the same log output:

`
homebridge     | [7/10/2020, 12:59:58 PM] [myQ] Invalid username or password given. Check your login and password.
homebridge     | [7/10/2020, 12:59:58 PM] [myQ] myQ API error: unable to refresh. Will retry later.
`

Homebridge version: 1.1.1
MyQ version: 2.1.2

**Comment by hjdhjd** [comment] 2020-07-16 13:54
Thanks - I’ve encountered the same issue and testing a fix. For the time being, reboot after a day or two and this should clear out. I’ll post a note when I push an update, but I want to ensure it’s decently tested. Thanks again!

**Comment by joebiber** [comment] 2020-07-16 13:57
Thank you good sir. Glad you found it too. I was worried it was just me... leading me to believe I had a failed/ impartial update / something else was going on that I'd have to track down. Restarting is easy enough for now, thanks for you hard work!

**Comment by javierhe** [comment] 2020-07-16 22:48
Hi, just wanted to let you know that I'm having this issue too. I'm on 2.1.2. Restarting the service solves the issue but I'm getting it back again. Let me know if you need more info. Thanks!

**Comment by hjdhjd** [comment] 2020-07-17 17:33
v2.1.3 is out...give this one a try.

**Comment by whreams** [comment] 2020-07-17 17:37
Just downloaded and tested a bit.  Looks good so far.

**Comment by hjdhjd** [comment] 2020-07-19 05:29
Closing this. Open a new report if needed. Thanks!

**Closed by hjdhjd** 2020-07-19 05:29 UTC
