### ISSUE TITLE
I updated to the new version today and my garage doors are not showing up at all.

### ISSUE THREAD

**Issue by markcsegal** [hjdhjd/homebridge-myq2#72] opened 2020-07-06 15:13 UTC
They were there in the old version and gone after installing the current one in NPM (2.1.0 according to the home bridge web based UI).  I removed all mention of the old plugin in the config manually, so no more error on startup.  in fact the API is connecting, see log below, but no devices.

[7/6/2020, 15:58:21] [MyQ2] Successfully connected to the myQ API.

Any thoughts?  Is there a cache I have to clear?

M

**Comment by kapee96** [comment] 2020-07-06 15:52
I have the same Issue. in the log i am getting the following error

node:4310) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/lib/node_modules/homebridge-myq2/dist/index.js:238:21
    at Array.forEach (<anonymous>)
    at myQPlatform.myQUpdateDeviceList (/usr/lib/node_modules/homebridge-myq2/src/index.ts:264:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at myQPlatform.updateAccessories (/usr/lib/node_modules/homebridge-myq2/src/index.ts:423:5)
(node:4310) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

**Comment by CAJensen01** [comment] 2020-07-06 17:19
Also having the same problem.

[7/6/2020, 12:15:21 PM] [myQ] Successfully connected to the myQ API.
[7/6/2020, 12:15:21 PM] [myQ] myQ garagedoor device discovered: Garage Door (serial number: XXX, gateway: GW23001C6102).
[7/6/2020, 12:15:21 PM] [myQ] myQ gateway device discovered: Hub (serial number: GW23001C6102).
(node:86615) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-myq2/dist/index.js:238:21
    at Array.forEach (<anonymous>)
    at myQPlatform.myQUpdateDeviceList (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:264:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at myQPlatform.updateAccessories (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:423:5)
(node:86615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:86615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:86615) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-myq2/dist/index.js:238:21
    at Array.forEach (<anonymous>)
    at myQPlatform.myQUpdateDeviceList (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:264:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at myQPlatform.updateAccessories (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:423:5)
(node:86615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:86615) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-myq2/dist/index.js:238:21
    at Array.forEach (<anonymous>)
    at myQPlatform.myQUpdateDeviceList (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:264:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at myQPlatform.updateAccessories (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:423:5)
(node:86615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:86615) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-myq2/dist/index.js:238:21
    at Array.forEach (<anonymous>)
    at myQPlatform.myQUpdateDeviceList (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:264:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at myQPlatform.updateAccessories (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:423:5)
(node:86615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:86615) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-myq2/dist/index.js:238:21
    at Array.forEach (<anonymous>)
    at myQPlatform.myQUpdateDeviceList (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:264:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at myQPlatform.updateAccessories (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:423:5)
(node:86615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:86615) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-myq2/dist/index.js:238:21
    at Array.forEach (<anonymous>)
    at myQPlatform.myQUpdateDeviceList (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:264:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at myQPlatform.updateAccessories (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:423:5)

**Comment by suedehed** [comment] 2020-07-06 19:19
Same issue since upgrading today

(node:3078) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/local/lib/node_modules/homebridge-myq2/dist/index.js:238:21
    at Array.forEach (<anonymous>)
    at myQPlatform.myQUpdateDeviceList (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:264:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at myQPlatform.updateAccessories (/usr/local/lib/node_modules/homebridge-myq2/src/index.ts:423:5)

**Comment by r0ballis0n** [comment] 2020-07-06 21:37
My door did not show up after the update either, but my error was looking for a plugin that was not found. I looked in the config and it was still asking for MyQ and not MyQ2. I added a 2 and saved the config and now my door is back. It did show up as a new device so I had to reconfigure my automation and scenes.

**Comment by sonoseco** [comment] 2020-07-06 23:55
Same error here as other have reported: Cannot read property 'getCharacteristic'.

**Comment by hjdhjd** [comment] 2020-07-07 02:10
If you’re still having problems, look at #71 - which this is a duplicate of.

As a temporary workaround, if you need to be up and running:

`npm install homebridge-myq2@2.0.13`

Duplicate of #71

**Closed by hjdhjd** 2020-07-07 02:10 UTC

**Comment by hjdhjd** [comment] 2020-07-07 02:11
Closing this one to keep this issue consolidated on one trail #71
