### ISSUE TITLE
Garage door shows up; gate does not

### ISSUE THREAD

**Issue by jaredhobbs** [hjdhjd/homebridge-myq2#64] opened 2020-07-05 04:14 UTC
I have both a garage door opener and a gate opener. Both the garage door and gate show up in the logs but only the garage door is showing up in the Home app. For both openers, the logs say "garagedoor discovered". Any hints on how to get the gate opener working again? Was working great prior to the July 1st changes.

**Comment by hjdhjd** [comment] 2020-07-05 06:24
Sounds like you’ve got a device that I haven’t accounted for yet. Can you post the portion of the log showing what devices the myQ API discovered? You can redact serial numbers for privacy, of course.

**Comment by jaredhobbs** [comment] 2020-07-05 15:07
[7/5/2020, 15:50:01] [myQ] Successfully connected to the myQ API.
[7/5/2020, 15:50:01] [myQ] myQ garagedoor device discovered: Garage door - CGXXXXXXXXXX.
[7/5/2020, 15:50:01] [myQ] myQ garagedoor device discovered: Gate - CGXXXXXXXXXX.
[7/5/2020, 15:50:01] [myQ] myQ gateway device discovered: MyQ Hub - GWXXXXXXXXXX.

**Comment by hjdhjd** [comment] 2020-07-05 15:37
Hmm. Well that’s fascinating. They both show up as a garage door device...but you’re saying that only one accessory exists in HomeKit? Unfortunately, I don’t have two garage door openers myself so it’s harder for me to test this setup directly, but it should work just fine. Can you confirm what myQ devices you see in the Home app?

**Comment by jaredhobbs** [comment] 2020-07-05 16:10
The first one, Garage door, is the only one showing up in the Home app now. Prior to the api change, both the garage door and gate opener showed up.

**Comment by MrCmonster** [comment] 2020-07-05 16:21
Just to add, I have two garage doors and they **are** both showing up. Just wanted to say thanks @hjdhjd and let you know that part is working for me.
```
[7/5/2020, 12:19:59 PM] [Garage] Successfully connected to the myQ API.
[7/5/2020, 12:19:59 PM] [Garage] myQ garagedoor device discovered: Drawbridge - CGXXXXXXXXXX.
[7/5/2020, 12:19:59 PM] [Garage] myQ gateway device discovered: Drawbridge - GWXXXXXXXXXX.
[7/5/2020, 12:19:59 PM] [Garage] myQ gateway device discovered: Home - GWXXXXXXXXXX.
[7/5/2020, 12:19:59 PM] [Garage] myQ garagedoor device discovered: Moat - CGXXXXXXXXXX.
[7/5/2020, 12:19:59 PM] [Garage] myQ gateway device discovered: Moat - GWXXXXXXXXXX.
```

**Comment by jaredhobbs** [comment] 2020-07-05 16:34
Looks like you have multiple gateway devices as well. I think in my setup, only the garage door opener acts as a gateway device and the gate opener connects through the garage door opener.

**Comment by MrCmonster** [comment] 2020-07-05 16:37
Good point. Each opener is its own gateway.

**Comment by johnacook-123** [comment] 2020-07-05 16:47
Hi I have the same issue, on the last plugin version both a gate and a garage door showed up as accessories, after the update only the garage door is showing but it does show it discovered the gate in the log. I have a single bridge. Thank you.

**Comment by AndreasMenrad** [comment] 2020-07-05 18:06
I have only one garage door but it is not showing up. Log seems to show it found everything successfully. I have one gateway and a commercial garage door opener -> Logic 5.0 Model T

[37m[7/5/2020, 1:38:27 PM] [39m[36m[myQ] [39mSuccessfully connected to the myQ API.
[37m[7/5/2020, 1:38:27 PM] [39m[36m[myQ] [39mmyQ garagedoor device discovered: Garage Door - CG09XXXXXXXX.
[37m[7/5/2020, 1:38:27 PM] [39m[36m[myQ] [39mmyQ gateway device discovered: MyQ TheMarx - GW21XXXXXXXX.

**Comment by RyanRadly** [comment] 2020-07-05 21:00
Having a similar issue. I have one gate opener and the necessary gateway for it; the myQ app displays it as expected, the logs in Homebridge loading show:

[7/5/2020, 3:54:35 PM] [myQ] myQ garagedoor device discovered: Gate - CG0A6XXXXX
[7/5/2020, 3:54:35 PM] [myQ] myQ gateway device discovered: Internet Gateway - GW01XXXXXX.

No accessories appear in Homebridge.

**Comment by hjdhjd** [comment] 2020-07-05 23:26
Hi guys...I’ve been watching this all day. I’m not sure exactly what’s going on, but let’s work to troubleshoot it...first...can you please update to the latest version (just released): v2.0.11...let’s start from a common base.

Then...if there’s someone on this thread that can be around and responsive over the next couple of hours, please let me know and we can work this issue and hopefully get it solved. Anyone around?

**Comment by RyanRadly** [comment] 2020-07-05 23:48
Hey @hjdhjd - I can be around for awhile!

In going to update the plugin, I had this error in the logs:

[myQ] Fetch error encountered: FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/d96daf11-0de4-451e-9e23-00ee5dd37786/Devices?filterOn=true failed, reason: read ECONNRESET

At any rate, updated to .11 and restarted Homebridge - API fetched as expected, but still not being exposed to HomeKit from HomeBridge.

**Comment by jaredhobbs** [comment] 2020-07-05 23:58
I'm also around. Updated to the latest code. What can we do to help?

**Comment by AndreasMenrad** [comment] 2020-07-06 00:05
Thank you so much for working on this.
I just updated to the latest release and still the same. No errors, it recognizes the gateway and garage door opener in the logs, but nothing is showing up on the home app. I have a commercial garage door opener, not sure if that makes any difference.

**Comment by hjdhjd** [comment] 2020-07-06 00:07
@RyanRadly That’s a normal error...it just means the connection got reset for one reason or another. I’d be concerned if it was a repeated thing. The plugin retries regularly to connect to the API. Alright, let’s focus on the task at hand...

**Comment by hjdhjd** [comment] 2020-07-06 00:08
So guys - can you provide the following information:

1. What is your exact physical setup (i.e. what myQ devices and openers do you actually have in your home(s))?
2. Please post the logs you see from v2.0.11, redacted for the serial numbers.

**Comment by AndreasMenrad** [comment] 2020-07-06 00:15
I have the Liftmaster 819LMB MyQ Home Bridge and a Commercial Garage Door Opener - Liftmaster Logic 5.0 Model T.
Log:
[7/5/2020, 8:14:03 PM] [myQ] Successfully connected to the myQ API.
[7/5/2020, 8:14:03 PM] [myQ] myQ garagedoor device discovered: Garage Door (serial number: CG09XXXXXXXX, gateway: GW21XXXXXXXX).
[7/5/2020, 8:14:03 PM] [myQ] myQ gateway device discovered: MyQ TheMarx (serial number: GW21XXXXXXXX).

**Comment by DMBlakeley** [comment] 2020-07-06 00:16
Physical setup: Chamberlain B550 garage door opener.
Logs:
`[7/5/2020, 8:10:22 PM] [MyQ2] Successfully connected to the myQ API.
[7/5/2020, 8:10:22 PM] [MyQ2] myQ gateway device discovered: Garage Door (serial number: GW0A00xxxxxx).
[7/5/2020, 8:10:22 PM] [MyQ2] myQ garagedoor device discovered: Garage Door Opener (serial number: CG0850xxxxxx, gateway: GW0A00xxxxxx).
`
Not experiencing any operational or notification issues.

**Comment by jaredhobbs** [comment] 2020-07-06 00:21
Liftmaster 8355W garage door opener; Liftmaster LA412UL gate opener

```
[7/6/2020, 00:29:45] [myQ] Successfully connected to the myQ API.
[7/6/2020, 00:29:45] [myQ] myQ garagedoor device discovered: Garage door (serial number: CGXXXXXXXXXX, gateway: GWXXXXXXXXXX).
[7/6/2020, 00:29:45] [myQ] myQ garagedoor device discovered: Gate (serial number: CGXXXXXXXXXX, gateway: GWXXXXXXXXXX).
[7/6/2020, 00:29:45] [myQ] myQ gateway device discovered: MyQ Hub (serial number: GWXXXXXXXXXX).
```

**Comment by hjdhjd** [comment] 2020-07-06 00:23
@AndreasMenrad I used to have that device!

So...what we’re seeing is that the API detects it, but for some reason we’re not adding the accessory. I assume everyone has tried clearing out cached accessories, and has verified that the accessory isn’t in the default room?

**Comment by hjdhjd** [comment] 2020-07-06 00:23
@DMBlakeley Good to see you here on this one. Are you running into issues as well?

**Comment by jaredhobbs** [comment] 2020-07-06 00:24
Correct, cleared cached accessories and only garage door opener shows up, no gate opener.

**Comment by hjdhjd** [comment] 2020-07-06 00:25
I got it.

**Comment by hjdhjd** [comment] 2020-07-06 00:25
Give me a few minutes, we’ll fix this right up.

**Comment by hjdhjd** [comment] 2020-07-06 00:25
`garagedoor` and `garagedooropener` are sadly different types.

**Comment by hjdhjd** [comment] 2020-07-06 00:25
Standby.

**Comment by DMBlakeley** [comment] 2020-07-06 00:37
@hjdhjd, no I am not seeing any issues. Thought you were looking for configurations good and bad. Didn't roll up to the problem for this posting.

**Comment by hjdhjd** [comment] 2020-07-06 00:48
Hot off the presses...try v2.0.12 guys. That should do the trick.

**Comment by hjdhjd** [comment] 2020-07-06 00:51
@DMBlakeley no worries. Welcome along for the ride...

What I’d love is to find someone who was using the battery feature in the older version of the plugin and see if we can get that going.

**Comment by AndreasMenrad** [comment] 2020-07-06 00:55
Just updated cleared cached devices and restarted. Sadly no change on my end.

**Comment by DMBlakeley** [comment] 2020-07-06 01:00
Eric Sandeen @sandeen submitted the original battery code. Assume that he had a battery to be able to test the code.

**Comment by hjdhjd** [comment] 2020-07-06 01:03
@AndreasMenrad Give me a few...

**Comment by cilianospina** [comment] 2020-07-06 01:06
Update no work for me, I restart server, and work few moment, and again same error!

**Comment by jaredhobbs** [comment] 2020-07-06 01:09
No change on my end either 😢. My garage door opener is still showing up in the Home app but the gate is not. Getting more info in the logs now though! (Possibly due to having debug set to true):

```
[7/6/2020, 01:49:48] [myQ] myQ garagedoor device discovered: Garage door (serial number: CGXXXXXXXXXX, gateway: GWXXXXXXXXXX).
[7/6/2020, 01:49:48] [myQ] {
   created_date: '2018-06-02T05:12:52.27',
   device_family: 'garagedoor',
   device_platform: 'myq',
   device_type: 'wifigaragedooropener',
   href: 'http://api.myqdevice.com/api/v5/accounts/<uuid>/devices/CGXXXXXXXXXX',
   name: 'Garage door',
   parent_device: 'http://api.myqdevice.com/api/v5/accounts/<uuid>/devices/GWXXXXXXXXXX',
   parent_device_id: 'GWXXXXXXXXXX',
   serial_number: 'CGXXXXXXXXXX',
   state: {
     attached_work_light_error_present: false,
     aux_relay_behavior: 'None',
     aux_relay_delay: '00:00:00',
     close: 'http://api.myqdevice.com/api/v5/accounts/<uuid>/devices/CGXXXXXXXXXX/close',
     command_channel_report_status: false,
     control_from_browser: false,
     door_ajar_interval: '00:00:00',
     door_state: 'closed',
     gdo_lock_connected: false,
     invalid_credential_window: '00:00:00',
     invalid_shutout_period: '00:00:00',
     is_unattended_close_allowed: true,
     is_unattended_open_allowed: true,
     last_status: '2020-07-06T00:48:47.0242156Z',
     last_update: '2020-07-06T00:13:12.7814557Z',
     max_invalid_attempts: 0,
     online: true,
     open: 'http://api.myqdevice.com/api/v5/accounts/<uuid>/devices/CGXXXXXXXXXX/open',
     passthrough_interval: '00:00:00',
     report_ajar: false,
     report_forced: false,
     rex_fires_door: false,
     use_aux_relay: false
   }
 }
[7/6/2020, 01:49:48] [myQ] myQ garagedoor device discovered: Gate (serial number: CGXXXXXXXXXX, gateway: GWXXXXXXXXXX).
[7/6/2020, 01:49:48] [myQ] {
   created_date: '2018-12-27T17:06:50.03',
   device_family: 'garagedoor',
   device_platform: 'myq',
   device_type: 'gate',
   href: 'http://api.myqdevice.com/api/v5/accounts/<uuid>/devices/CGXXXXXXXXXX',
   name: 'Gate',
   parent_device: 'http://api.myqdevice.com/api/v5/accounts/<uuid>/devices/GWXXXXXXXXXX',
   parent_device_id: 'GWXXXXXXXXXX',
   serial_number: 'CGXXXXXXXXXX',
   state: {
     aux_relay_behavior: 'None',
     aux_relay_delay: '00:00:00',
     close: 'http://api.myqdevice.com/api/v5/accounts/<uuid>/devices/CGXXXXXXXXXX/close',
     command_channel_report_status: false,
     control_from_browser: false,
     door_ajar_interval: '00:00:00',
     door_state: 'open',
     invalid_credential_window: '00:00:00',
     invalid_shutout_period: '00:00:00',
     is_unattended_close_allowed: true,
     is_unattended_open_allowed: true,
     last_status: '2020-07-06T00:45:06.5142548Z',
     last_update: '2020-07-02T14:27:48.2274557Z',
     max_invalid_attempts: 0,
     online: true,
     open: 'http://api.myqdevice.com/api/v5/accounts/<uuid>/devices/CGXXXXXXXXXX/open',
     passthrough_interval: '00:00:00',
     report_ajar: false,
     report_forced: false,
     rex_fires_door: false,
     use_aux_relay: false
   }
 }
[7/6/2020, 01:49:48] [myQ] myQ gateway device discovered: MyQ Hub (serial number: GWXXXXXXXXXX).
[7/6/2020, 01:49:48] [myQ] {
   created_date: '2018-06-02T05:12:52.257',
   device_family: 'gateway',
   device_platform: 'myq',
   device_type: 'wifigdogateway',
   href: 'http://api.myqdevice.com/api/v5/accounts/<uuid>/devices/GWXXXXXXXXXX',
   name: 'MyQ Hub',
   serial_number: 'GWXXXXXXXXXX',
   state: {
     firmware_version: '3.5',
     homekit_capable: false,
     homekit_enabled: false,
     last_status: '2020-07-05T18:45:42.7861173Z',
     learn: 'http://api.myqdevice.com/api/v5/accounts/<uuid>/devices/GWXXXXXXXXXX/learn',
     learn_mode: false,
     online: true,
     pending_bootload_abandoned: false,
     physical_devices: [ 'CGXXXXXXXXXX' ],
     updated_date: '2020-07-05T18:45:45.7969719Z'
   }
 }
[7/6/2020, 01:49:48] [myQ] Throttling myQ API call. Using cached data from the past five seconds.
```

**Comment by hjdhjd** [comment] 2020-07-06 01:10
Thanks guys...I’m working on it.

**Comment by hjdhjd** [comment] 2020-07-06 01:20
@jaredhobbs I know what the problem is, and I’m implementing a fix. Essentially, that device_type category is important...in an effort to not assume everything is compatible, I’ve taken a conservative view of what a garage door opener can be. The challenge is, it being an undocumented API and all, there’s no telling what all the different types are. SO...will be fixed soon.

**Comment by jaredhobbs** [comment] 2020-07-06 01:21
Awesome, great to hear. Thanks for all your work on this!

**Comment by AndreasMenrad** [comment] 2020-07-06 01:26
Here is my detailed log in debug mode. Hope it helps:

[7/5/2020, 9:21:59 PM] [myQ] {
  count: 2,
  href: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxx/devices',
  items: [
    {
      created_date: '2019-12-08T16:51:42.933',
      device_family: 'garagedoor',
      device_platform: 'myq',
      device_type: 'commercialdooropener',
      href: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxx/devices/CG09XXXXXXX',
      name: 'Garage Door',
      parent_device: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxx/devices/GW21XXXXXXXX',
      parent_device_id: 'GW21XXXXXXX',
      serial_number: 'CG09XXXXXXX',
      state: {
        aux_relay_behavior: 'None',
        aux_relay_delay: '00:00:00',
        close: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxx/devices/CG09XXXXXXX/close',
        command_channel_report_status: false,
        control_from_browser: false,
        door_ajar_interval: '00:00:00',
        door_state: 'closed',
        invalid_credential_window: '00:00:00',
        invalid_shutout_period: '00:00:00',
        is_unattended_close_allowed: true,
        is_unattended_open_allowed: true,
        last_status: '2020-07-06T01:18:16.6146922Z',
        last_update: '2020-07-05T22:18:26.1357032Z',
        max_invalid_attempts: 0,
        online: true,
        open: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxx/devices/CG09XXXXXXXXX/open',
        passthrough_interval: '00:00:00',
        report_ajar: false,
        report_forced: false,
        rex_fires_door: false,
        use_aux_relay: false
      }
    },
    {
      created_date: '2019-04-28T13:50:52.217',
      device_family: 'gateway',
      device_platform: 'myq',
      device_type: 'ethernetgateway',
      href: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxxx/devices/GW21XXXXXXX',
      name: 'MyQ TheMarx',
      serial_number: 'GW21XXXXXXXX',
      state: {
        firmware_version: '1.6',
        homekit_capable: false,
        homekit_enabled: false,
        last_status: '2020-07-05T17:45:14.4162039Z',
        learn: 'http://api.myqdevice.com/api/v5/accounts/xxxxxxxxxxxx/devices/GW21XXXXXXX/learn',
        learn_mode: false,
        online: true,
        pending_bootload_abandoned: false,
        physical_devices: [],
        updated_date: '2020-07-05T17:45:17.4228064Z'
      }
    }
  ]

**Comment by hjdhjd** [comment] 2020-07-06 01:27
THANKS!

**Comment by hjdhjd** [comment] 2020-07-06 01:30
Alright guys...let’s try lucky 13. 2.0.13 is out. This should do it.

**Comment by jaredhobbs** [comment] 2020-07-06 01:33
Boom! That fixed it for me. Great work! 👍

**Comment by hjdhjd** [comment] 2020-07-06 01:34
The debug output was most helpful. Thanks again.

**Comment by hjdhjd** [comment] 2020-07-06 01:35
@AndreasMenrad can you report back as well?

**Comment by AndreasMenrad** [comment] 2020-07-06 01:35
Awesome. It is working. Thank you so much working so hard on it.

**Comment by hjdhjd** [comment] 2020-07-06 01:36
Thanks all for your help and putting in some time with me tonight. Closing this one out.

**Closed by hjdhjd** 2020-07-06 01:36 UTC
