### ISSUE TITLE
Unhandled promise Rejection Warning

### ISSUE THREAD

**Issue by chriswcarter2** [hjdhjd/homebridge-myq2#85] opened 2020-07-11 21:02 UTC
I keep getting an "Unhandled promise Rejection Warning". I've tried removing and reinstalling the plugin with no improvement.

`(node:7813) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCharacteristic' of undefined
    at /usr/lib/node_modules/homebridge-myq2/dist/index.js:238:21
    at Array.forEach (<anonymous>)
    at myQPlatform.myQUpdateDeviceList (/usr/lib/node_modules/homebridge-myq2/src/index.ts:264:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at myQPlatform.updateAccessories (/usr/lib/node_modules/homebridge-myq2/src/index.ts:423:5)
(node:7813) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4616)`

**Comment by iRayanKhan** [comment] 2020-07-11 23:06
Might be an Api change/outage? See https://github.com/iRayanKhan/homebridge-chamberlain/issues/111

**Comment by hjdhjd** [comment] 2020-07-12 07:28
Duplicate of #71 

There's a fix in the thread as well that seems to work for most people. Please try that and see if it helps.

**Closed by hjdhjd** 2020-07-12 07:28 UTC
