### ISSUE TITLE
Some myq2 plugin errors seem to render all other homebridge accessories offline

### ISSUE THREAD

**Issue by sandeen** [hjdhjd/homebridge-myq2#38] opened 2020-06-26 16:32 UTC
When an error like hjdhjd/homebridge-myq2/issues/32 happens, it seems to render all other homebridge plugins offline.  I still see updates in the homebridge log, but the native ios homekit app shows no updates for any accessories

**Comment by sandeen** [comment] 2020-06-26 16:33
Sorry no PR for now, but adding error handling like this seems to fix it for me - not sure if it's the right approach or not, or if maybe the whole loop should eventually shut down if certain fatal/permanent login errors are returned.

```
--- a/index.js	2020-05-31 14:03:03.973635105 -0500
+++ b/index.js	2020-06-25 21:25:05.956742499 -0500
@@ -97,6 +98,9 @@
           self.updateDoorStates(accessory);
         }
       }
+    } else {
+          self.log('addAccessory: login failed');
+          self.removeAccessory(accessory);
     }
   });
 }
@@ -217,6 +227,7 @@
     }
   }).catch(error => {
       self.log('Login error: ' + error);
+      callback(error);
   });
 }
```

**Comment by sandeen** [comment] 2020-06-26 16:51
https://github.com/sandeen/homebridge-myq2/tree/fix-dead-homebridge

**Comment by shamoon** [comment] 2020-06-27 03:30
Cheers was thinking of writing this up too. I’m not sure you need to remove the accessory or not. But I’m pretty sure the important part is to call the `callback` as you did. (I’m not testing just looking at your code)

See https://github.com/homebridge/homebridge/issues/948

**Comment by sandeen** [comment] 2020-06-27 03:42
Ah, that makes more sense, reading the other issue, thanks.

Not sure why I was removing the accessory tbh ;)

**Comment by DMBlakeley** [comment] 2020-06-27 14:27
As a test I added just the `callback(error);` line to my archive. I then changed `myQ/19569` back to `myQ/14041` and restarted Homebridge. The Garage Door shows as no response in Homebridge and other devices are not blocked. The error log repeatibly shows:

`[6/27/2020, 10:10:07 AM] [Garage Door] Login error: FetchError: invalid json response body at https://myqexternal.myqdevice.com/api/v4/User/Validate reason: Unexpected number in JSON at position 115`

Probably need to improve the error logging so that the problem is better described and only logs once.

Do not think that you should remove accessory as this step will remove the Garage Door from your HomeKit Scenes.

**Comment by shamoon** [comment] 2020-06-27 14:50
@sandeen I submitted an update to your fork and then you can create a PR here, that way you get credit for your work =)

**Comment by sandeen** [comment] 2020-06-27 15:36
Cool, thank you both.

If you're bored, want to take a look at my battery status PR? :) pull/26

**Comment by shamoon** [comment] 2020-06-27 17:56
I submitted PR #41 for this, it delays login attempts by progressively longer to avoid hammering MyQ servers. This plugin is in need of some more serious reworking but for now this should work assuming #40 gets merged.

**Comment by pponce** [comment] 2020-06-27 23:23
@sandeen I merged your battery status PR into my fork, long with a few other of the PR's in the queue right now.
Where in the home app should i see the battery status?

**Comment by sandeen** [comment] 2020-06-28 00:24
@pponce Er, let me look, I'm afraid I did some last minute "trivial" variable renaming and maybe I broke it.... *sigh* yes.

To fix it, change the one instance of `currentBattery` to `batteryStatus`

Then I think you won't see anything unless the state is low, so you could manually set

`newBattery = Characteristic.StatusLowBattery.BATTERY_LEVEL_LOW;`

outside of the if/else code.  I guess I should revoke that PR and fix it, sorry about that.

**Comment by hjdhjd** [comment] 2020-06-28 02:38
Fixes are in. Update away folks. Thanks!

**Closed by hjdhjd** 2020-06-28 02:38 UTC

**Comment by pponce** [comment] 2020-06-28 04:28
@sandeen No apology needed. Just wanted to make sure i was not missing anything.
Thanks for adding this battery check!

**Comment by maelstromchanneled** [comment] 2020-06-28 22:51
I just logged in a saw this issue is closed and verified it on my home setup.  I just want to say a BIG thank you to this awesome community for all that you do to make homebridge and homebridge platforms and accessories a viable solution!  Thank you!
