### ISSUE TITLE
Unexpected number in JSON at position 115

### ISSUE THREAD

**Issue by sebastiangoldstein** [hjdhjd/homebridge-myq2#34] opened 2020-06-25 20:28 UTC
I was having some naming issues with the Garage Doors so I uninstalled and reinstalled.
Now garage doors won't show up in HomeKit
and I keep getting this error in the Log:
https://myqexternal.myqdevice.com/api/v4/User/Validate reason: Unexpected number in JSON at position 115

**Comment by andrewturko** [comment] 2020-06-25 20:30
This is very likely a duplicate of #32, of which [this comment](https://github.com/hjdhjd/homebridge-myq2/issues/32#issuecomment-649787215) references a fix for.

**Comment by TheEngineerGuy** [comment] 2020-06-25 23:29
I have performed now changes for quite a few days, but since this morning I am getting this error as well. Seems to be some change on MyQ service end.

Looking at the previous comment, we possibly need a similar fix on this plugin as well.

**Comment by DMBlakeley** [comment] 2020-06-25 23:32
See issue #32 which is the same problem. Solution posted in that conversation. I have submitted PR to correct but as I am not owner cannot release.

**Comment by TheEngineerGuy** [comment] 2020-06-25 23:34
Thanks @DMBlakeley Appreciate it bud.

**Comment by hjdhjd** [comment] 2020-06-28 02:41
Fixed in the latest update.

**Closed by hjdhjd** 2020-06-28 02:41 UTC
