### ISSUE TITLE
 Error getting MyQ devices: undefined

### ISSUE THREAD

**Issue by RCdiy** [hjdhjd/homebridge-myq2#44] opened 2020-07-01 17:35 UTC
Was working yesterday.

[7/1/2020, 13:33:20] [MyQ2] Error getting MyQ devices: undefined
[7/1/2020, 13:33:36] [MyQ2] Error getting MyQ devices: undefined
[7/1/2020, 13:33:44] [Config] Starting terminal session

**Comment by 33racerx** [comment] 2020-07-01 18:06
[7/1/2020, 11:04:54 AM] [MyQ] Error getting MyQ devices: Unauthorized (216)

Similar message, just started getting this today.

**Comment by cryptobrian** [comment] 2020-07-01 18:07
Same here.  I also tried using the chamberlain plugin, and it is also not working.
Looks like Chamberlain changed something on their side again.

MyQ2 plugin error:
Error getting MyQ devices: undefined

Chamberlain plugin error:
Error: invalid response, got HTTP 401: {"code":"401.203","message":"Unauthorized","description":"The username or password you entered is incorrect. Try again."}

**Comment by RyanRadly** [comment] 2020-07-01 18:09
I'm getting the same message @33racerx is getting, verbatim.

**Comment by armandr** [comment] 2020-07-01 18:16
Same here:

`[MyQ2] Error getting MyQ devices: undefined
 [MyQ2] Error getting MyQ devices: Unauthorized (216)`

Running the latest version.  It was working yesterday.

**Comment by whreams** [comment] 2020-07-01 18:30
Same here.  I’m sure the HB developer team is on it!  Thanks guys!!!

**Comment by kydav** [comment] 2020-07-01 19:28
I'm having the same issue, but it could be an issue with Chamberlain.  I am able to get in through the app, but if I try the same login on their site, it says it is incorrect.

**Comment by LordZork** [comment] 2020-07-01 19:46
I'm having the same issue as others here... probably everyone...

@kydav This may be a dumb question, but what site did you try logging into – chamberlain.com?  That's the only site I'm aware of (since you can't log into their myQ site), and I had the same experience ("Your username or password was incorrect").  I tried the "Forgot your password?" option (even though I know my password and know it's correct), but haven't received a password-reset email.

Chamberlain is super annoying...

**Comment by kydav** [comment] 2020-07-01 19:52
@LordZork I tried the same things, still no password reset email and it's been several hours.  I logged in here: https://www.chamberlain.com/login

**Comment by LordZork** [comment] 2020-07-01 21:21
Note regarding website login issues...

Working (_successful_ login and password-reset):
https://www.mychamberlain.com/
https://www.myliftmaster.com/

Not working (_unsuccessful_ login and password-reset):
https://www.chamberlain.com/

The plugin has been broken twice in less than a month.  I am nervous that myQ is actually making efforts to thwart Homebridge support, since they can't profit from it.  They have their own HomeKit-enabled hub, which is an extra and otherwise-unneeded device and expense, and they charge for IFTTT integration, etc.  Hopefully this is not the case, and hopefully we get a fix/updated plugin that resolves the issue.  

Regardless, Chamberlain/myQ has the worst third-party support, integration, and "partnerships."  They are terrible, and recently lost Wink support – one of the few partnerships they've had – because of their stupid and excessive partner requirements and fees.

**Comment by DMBlakeley** [comment] 2020-07-02 01:12
myQ updated the iOS app to version 5.158 on June 29. How do you find out the build number for this version?

**Comment by DMBlakeley** [comment] 2020-07-02 01:22
Found the build number, it is at the bottom of the myQ app Account page. Current build is 19859. Unfortunately, this change does not fix the issue.

**Comment by TheEngineerGuy** [comment] 2020-07-02 03:01
Hey @DMBlakeley Any speculation on this one?

I am beginning to agree with @LordZork , this is starting look malicious. Their own HB product was so bad I gave it away, and now they are perpetually in a broken state for HB plugin. Doesn't seem very promising.

**Comment by Danimal4326** [comment] 2020-07-02 04:14
Did some digging, looks like they aren't letting the login go through, so there is no token passed:

'''
{
  SecurityToken: '',
  ReturnCode: '0',
  ErrorMessage: 'please contact customer care, supportID: 712915074050492145',
  CorrelationId: ''
}';
'''

**Comment by TheEngineerGuy** [comment] 2020-07-02 04:31
So two possibilities that I can think of:

1. They did it only to the URL that we are using. Which can be fixed by using other URLs like connect.mydevice.com. 

2. They cut off 4.1 calls off as part of their deprecation measures. Assuming that you made 4.1 call to get that response.

**Comment by pponce** [comment] 2020-07-02 04:50
I was able to authenticate/login with v5.1 api call.
Also able to pull list of devices with v5.1 api call.
Your hunch about deprecating v4 is probably right.

**Comment by Danimal4326** [comment] 2020-07-02 04:57
This is from the plugin (just added some extra logging)

@pponce how did you do the v5.1 api call?

**Comment by shamoon** [comment] 2020-07-02 05:11
Yes @pponce if you can provide URL/headers for v5 call would be helpful to start seeing what else needs updating.

**Comment by pponce** [comment] 2020-07-02 05:26
here are the two api calls i was able to make.

myq login
https://api.myqdevice.com/api/v5/Login

headers:
Content-Type:application/json
User-Agent:myQ/19569 CFNetwork/1107.1 Darwin/19.0.0
MyQApplicationId:JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu
ApiVersion:5.1

get devices and status
http://api.myqdevice.com/api/v5.1/Accounts/{{AccountID}}/Devices

headers:
Content-Type:application/json
User-Agent:myQ/19569 CFNetwork/1107.1 Darwin/19.0.0
MyQApplicationId:JVM/G9Nwih5BwKgNCjLxiFUQxQijAebyyg8QUHr7JOrP+tuPb8iHfRHKwTmDzHOu
ApiVersion:5.1

**Comment by shamoon** [comment] 2020-07-02 05:34
https://api.myqdevice.com/api/v5/My
headers: {{security-token}}

I'll see if I can get things back on track...

**Comment by TheEngineerGuy** [comment] 2020-07-02 06:02
Ok good. So we know what the problem is. Let’s get going on the api v5. Easy for me to say. But looks like that is the only way forward.

**Comment by shamoon** [comment] 2020-07-02 07:25
I have not extensively tested this (its the middle of the night! 🤪 ) but I have updated the current plugin to work with v5 API, see PR #47. We'll need @hjdhjd to merge when he's available.

**Comment by hjdhjd** [comment] 2020-07-02 07:29
I appreciate the time you took to take this on, but I won't be merging this. I'm in the midst of refactoring this plugin and I'll be publishing something in the next day or two. Bear with me guys, it's a huge update and I want to ensure it's working well before I publish it.

**Comment by hjdhjd** [comment] 2020-07-02 07:32
For those experiencing errors: myQ deprecated most non-v5 APIs on July 1. It's not a coincidence. :smile: Just a few hours more I hope and I'll have an update here. I have this working well on my own development tree.

**Comment by LordZork** [comment] 2020-07-02 08:32
@hjdhjd Thanks for chiming in and letting us know, and for your efforts in updating your plugin.  I'm sure I speak for many when I say, the plugin and the work that goes into it is very much appreciated!!  Thank you!!

**Comment by TheEngineerGuy** [comment] 2020-07-02 14:55
All good @hjdhjd . Take your time, we can wait for it to be done right.

**Comment by DMBlakeley** [comment] 2020-07-02 15:38
@hjdhjd, thanks for your efforts! I am sure that if you were looking for a limited test group there would be a couple of regulars that would be happy to volunteer.

**Comment by hjdhjd** [comment] 2020-07-02 15:39
Thanks all. I'll be posting something later today. Hopefully it all goes off without a hitch. :smile:

**Comment by DMBlakeley** [comment] 2020-07-02 16:06
One suggestion I might make is to add the build number as a config parameter as this seems to be the most frequent breaking change.

**Comment by Gilmargolin** [comment] 2020-07-02 18:20
I am getting this error: 
[MyQ2] Error: Couldn't find a MyQ door device.

**Comment by TheEngineerGuy** [comment] 2020-07-02 18:31
> I am getting this error:
> [MyQ2] Error: Couldn't find a MyQ door device.

Sorry, I fail to see how your issue is related to this thread. Check for another thread which is more relevant, if not please create a new thread.

**Comment by Gilmargolin** [comment] 2020-07-02 18:46
I updated to the v5-api branch and I am now getting a new error, all was working fine two days ago.

**Comment by shamoon** [comment] 2020-07-02 18:54
@Gilmargolin the repo owner has said he won’t be merging that branch in because he has been working on a larger revamp of the plugin which presumably includes the v5 API. As such, unless we hear otherwise, it’s probably not worth tracking down that error since he said he would be publishing his update today.

**Comment by joeria100** [comment] 2020-07-02 20:33
Thanks hjdhjd.  Appreciate your work on this and really appreciate the functionality!

**Comment by jiniej** [comment] 2020-07-02 21:40
I would like to second joeria100, thanks hjdhjd!

**Comment by hjdhjd** [comment] 2020-07-03 00:16
Thanks all. Just a quick update...making good progress and hoping to get this released today or tomorrow. Real life interferes at times. :)

Oh...and getting repeatedly locked out of myQ servers for polling too much. Seems that they've at least improved the auto banning they use to falloff after 10-15 minutes. But...you can imagine when you hit it, having to wait feels like an eternity.

**Comment by bwoodruff** [comment] 2020-07-03 01:03
Thank you for the update @hjdhjd. Would it be possible along with these changes to make it such that API changes don't cause the accessory to be removed from HomeKit (causing automations to break)? This behavior is better than the previous behavior of breaking all HomeBridge accessories, I suppose, but I'd think the ideal outcome would be for _just_ the garage door accessories added by myq2 to go 'not responding' (yet remain in HomeKit).

Many thanks for building this. Despite the few recent problems because of API changes I've found it to be more reliable than Chamberlain's "Home Bridge" hardware.

**Comment by christianguitarfreak** [comment] 2020-07-03 01:04
Thanks @hjdhjd for your work on this! I really appreciate it.

**Comment by hjdhjd** [comment] 2020-07-03 01:06
@bwoodruff I have the hardware device too and specifically use this plugin because it's such an unreliable device. In a separate thread we can commiserate on the badness of the hardware bridge. On the plus side...I've inadvertently discovered how to make it more stable when doing some other network upgrades over the past few weeks.

As to the ask on automations...I have the same issue and it's something I'm hoping to address, but unlikely in the first release or two of the refactored plugin. It's very high on my list though...I have automations and I hate redoing them too. :smile:

**Comment by shamoon** [comment] 2020-07-03 02:02
Obviously appreciate your work and if you prefer to wait for your update to be ready thats your call. But I will say there are two PRs currently pending which address both the lockout (PR #41) and v5 API (PR #47). Obviously those might bring their own bugs so again, I get it if not, but just sayin if you think you need more time...

**Comment by seanxushen** [comment] 2020-07-03 14:40
@hjdhjd Any update when you will post fixed plugin ?

**Comment by hjdhjd** [comment] 2020-07-04 01:43
Alright all, v2.0 of the plugin is out. Hopefully all goes well. :smile:

**Comment by cryptobrian** [comment] 2020-07-04 01:45
Wow! You’re awesome.  Thanks so much! Upgrading now!

**Comment by hjdhjd** [comment] 2020-07-04 01:45
All, given how long this thread is now, I'm going to close out this issue and ask that you guys beat on v2.0 and open new issues for anything you uncover.

Thanks!

**Closed by hjdhjd** 2020-07-04 01:45 UTC

**Comment by guppstir** [comment] 2020-07-04 11:46
Thank You for the update. 
Tip: You'll want to make sure you uninstall and reinstall or just delete the old config settings first.

**Comment by kbrashears5** [comment] 2020-07-04 13:27
Something to note - in your config.json you need to change platform from MyQ2 to myQ - and it is case sensitive

**Comment by RCdiy** [comment] 2020-07-04 13:33
Using the web ui I clicked update. It started immediately without first showing the release notes. After the update the settings link is missing. 
Web ui
iPod touch
Safari

**Comment by whreams** [comment] 2020-07-04 13:38
I did the below and all is working as expected.

**Comment by DMBlakeley** [comment] 2020-07-04 13:42
I waited for the overnight dust to settle. This morning, uninstalled previous version via web interface (which also removes config.json settings), restarted Homebridge, installed latest myq2 version (2.0.8), entered credentials, restarted Homebridge, and MyQ started up very smoothly with the garage door being added in seconds.

Yes, by uninstalling you will lose your present garage door in any Favorite Scenes or Automations but this step ensures that all the naming conventions are correct.

**Comment by joeria100** [comment] 2020-07-04 13:56
Hi,

Sorry to bug you.  I uninstalled and reinstalled on Polisy and readded my credentials, yet the garage door nodes do not populate in polisy.  Continue to get no devices message in the log (attached).  Ive double checked my credentials and they are correct.

What should I look at?

Thanks,
Joe

Joseph R. Iantosca, CRISC, CDPSE
JRIantosca@gmail.com<mailto:JRIantosca@gmail.com> | 732-616-7770<tel:732-616-7770>
