### ISSUE TITLE
Occasional Fetch Error

### ISSUE THREAD

**Issue by whreams** [hjdhjd/homebridge-myq2#94] opened 2020-07-21 12:51 UTC
Symptoms just started with v 2.14.  The door works but unsure why the below has started to show up.

Node.js Version: v12.16.3
Npm Version: v6.14.4
homebridge-myq2: v2.1.4

[7/21/2020, 7:15:19 AM] [myQ] FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/de9b8700-73a9-4f7e-be5a-35f49acfc174/Devices failed, reason: connect ETIMEDOUT 13.83.97.206:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-myq2/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
[7/21/2020, 7:15:19 AM] [myQ] myQ API: unable to refresh. Acquiring a new security token and retrying later.
[7/21/2020, 7:15:19 AM] [myQ] myQ API: successfully acquired a new security token.
[7/21/2020, 7:15:19 AM] [myQ] Polling error: unable to connect to the myQ API.

**Comment by markcsegal** [comment] 2020-07-21 14:22
I see this too.  Started the version before.  I see a slightly different error.



[7/21/2020, 15:04:08] [myQ] FetchError: request to https://api.myqdevice.com/api/v5.1/Accounts/7a9ac2d4-0ff6-41ef-bfd1-db7782a19057/Devices failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-myq2/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
[7/21/2020, 15:04:08] [myQ] myQ API: unable to refresh. Acquiring a new security token and retrying later.
[7/21/2020, 15:04:08] [myQ] myQ API: successfully acquired a new security token.
[7/21/2020, 15:04:08] [myQ] Polling error: unable to connect to the myQ API.

**Comment by abhollan** [comment] 2020-07-21 17:48
I'm getting this too

**Comment by TheEngineerGuy** [comment] 2020-07-22 01:48
Guys, I think we have addressed this multiple times, but here we are again. We do not control the MyQ servers, so these errors are bound to happen when plugin to server communication gets interrupted for some reason.

As long as plugin keeps on working after the error, please ignore it. It clearly says that it will try again, and then it tries again and things keep on working. What else do you think can be done here?

**Comment by DMBlakeley** [comment] 2020-07-22 02:14
I would add that “control of servers” is common to many (all?) of the homebridge plugins. The accessory in your house is communicating one way to the accessory server. Homebridge in turn is polling this sever, possibly sending a command to the server, which in turn sends a command to the accessory. So, 4 internet communications to control the device. This is in contrast to a native Homekit device where all communications are within the local network.

Accessories which we are trying to control with homebridge that we want “real time” control struggle the most. Garage doors, security cameras, doorbells, and others fall in this category. I have found that making sure that you have a clean network at your house with good WiFi integrity to your devices is a first step. I have also found in my case that using a DNS service (Cloudflare) provides a bit better response that you default from your ISP (Spectrum in my case).

Agree with @TheEngineerGuy that errors are not necessarily bad as long as there is clean recovery which appears to be the case with MyQ. Not sure requesting a new token each time is necessary but doesn’t appear to be causing additional problems and ensures that MyQ server queries are in a known state.

**Comment by hjdhjd** [comment] 2020-07-22 02:17
This is not a bug. These failures have always happened, but I've chosen to inform the user versus silently ignoring them. They are unconcerning unless they are happening constantly, which would indicate an API error. Closing this one.

Thanks all.

**Closed by hjdhjd** 2020-07-22 02:17 UTC

**Comment by whreams** [comment] 2020-07-22 13:18
Thanks to @hjdhjd  @DMBlakeley and @TheEngineerGuy for the explanation and work.  I only started using the plugin around November of ’19 and suspect there’s a longer history of how Chamberlain has supported this part of the business.  Totally get the explanation and the decision on how to handle.  Thank you for explaining, and on the plugin work.
